/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-surface-variant": "#4d4638",
        "on-secondary-fixed": "#220f47",
        "surface-tint": "#765a0e",
        "secondary-fixed": "#eaddff",
        "surface-container-lowest": "#ffffff",
        "surface": "#fff8f2",
        "on-secondary-container": "#5a4882",
        "on-primary-container": "#795d11",
        "on-tertiary-fixed": "#002114",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#aeebcb",
        "outline": "#7f7666",
        "surface-variant": "#e9e1d8",
        "on-tertiary-fixed-variant": "#125139",
        "surface-container": "#f5ede3",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdf99",
        "tertiary-fixed": "#b2f0cf",
        "surface-bright": "#fff8f2",
        "on-primary-fixed-variant": "#5a4300",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e9e1d8",
        "primary-container": "#ffd982",
        "surface-container-low": "#fbf2e8",
        "primary-fixed-dim": "#e6c26e",
        "secondary": "#67548f",
        "tertiary-fixed-dim": "#97d3b4",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#4e3d76",
        "tertiary": "#2f694f",
        "inverse-on-surface": "#f8f0e6",
        "error-container": "#ffdad6",
        "on-surface": "#1e1b15",
        "on-background": "#1e1b15",
        "background": "#fff8f2",
        "inverse-surface": "#343029",
        "surface-dim": "#e0d9cf",
        "on-tertiary-container": "#326c52",
        "outline-variant": "#d0c5b3",
        "surface-container-high": "#efe7dd",
        "on-primary-fixed": "#251a00",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#d1bcff",
        "primary": "#765a0e",
        "secondary-container": "#d1bcff",
        "inverse-primary": "#e6c26e",
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "unit": "8px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ["\"Libre Caslon Text\"", "serif"],
        "headline-lg-mobile": ["\"Libre Caslon Text\"", "serif"],
        "body-md": ["\"Plus Jakarta Sans\"", "sans-serif"],
        "display-lg": ["\"Libre Caslon Text\"", "serif"],
        "headline-lg": ["\"Libre Caslon Text\"", "serif"],
        "label-sm": ["\"Plus Jakarta Sans\"", "sans-serif"],
        "label-bold": ["\"Plus Jakarta Sans\"", "sans-serif"],
        "body-lg": ["\"Plus Jakarta Sans\"", "sans-serif"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          {
            lineHeight: "1.3",
            fontWeight: "600",
          },
        ],
        "headline-lg-mobile": [
          "28px",
          {
            lineHeight: "1.2",
            fontWeight: "700",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "1.5",
            fontWeight: "400",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "1.2",
            fontWeight: "700",
          },
        ],
        "label-sm": [
          "12px",
          {
            lineHeight: "1.2",
            fontWeight: "600",
          },
        ],
        "label-bold": [
          "14px",
          {
            lineHeight: "1.2",
            fontWeight: "700",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "1.6",
            fontWeight: "500",
          },
        ],
      },
    },
  },
  plugins: [],
}
